/**
 * PDF generation utilities for HealthPredict reports.
 * Uses jsPDF + jspdf-autotable.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const BRAND = { name: "HealthPredict", color: [37, 99, 235] as [number, number, number] };

export type ReportType = "patient" | "system" | "model" | "quick";

export type ReportContext = {
  type: ReportType;
  title: string;
  doctor?: string;
  institution?: string;
  patient?: { name: string; age?: number | null; gender?: string | null; contact?: string | null };
  dateRange?: { from?: string; to?: string };
  sections: {
    executive?: { total: number; low: number; medium: number; high: number };
    predictions?: Array<{
      created_at: string;
      disease_type: string;
      risk_level: string | null;
      risk_score: number | null;
      confidence: number | null;
      model_used?: string | null;
    }>;
    models?: Array<{
      model_name: string;
      disease_type: string | null;
      accuracy: number | null;
      f1_score: number | null;
      auc_roc: number | null;
    }>;
    featureImportance?: Record<string, number>;
    recommendations?: string[];
  };
};

function header(doc: jsPDF, title: string) {
  doc.setFillColor(...BRAND.color);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`${BRAND.name} · ${title}`, 14, 12);
  doc.setTextColor(0, 0, 0);
}

function footer(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`${BRAND.name} · AI Disease Prediction Suite`, 14, h - 8);
    doc.text(`Page ${i} of ${pageCount}`, w - 28, h - 8);
    doc.setTextColor(0);
  }
}

export function generateReportPdf(ctx: ReportContext): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();

  // ====== Cover ======
  doc.setFillColor(...BRAND.color);
  doc.rect(0, 0, w, 80, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text(BRAND.name, 14, 38);
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Based Smart Healthcare Disease Prediction", 14, 48);
  doc.setFontSize(11);
  doc.text(ctx.title, 14, 62);

  doc.setTextColor(0);
  let y = 100;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Report Details", 14, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const lines = [
    `Generated: ${new Date().toLocaleString()}`,
    `Institution: ${ctx.institution ?? "—"}`,
    `Generated by: ${ctx.doctor ?? "—"}`,
    `Report type: ${ctx.type.toUpperCase()}`,
    ctx.dateRange?.from || ctx.dateRange?.to
      ? `Date range: ${ctx.dateRange?.from ?? "…"} → ${ctx.dateRange?.to ?? "…"}`
      : "",
  ].filter(Boolean);
  lines.forEach((l) => {
    doc.text(l, 14, y);
    y += 6;
  });

  // ====== Patient Details ======
  if (ctx.patient) {
    doc.addPage();
    header(doc, "Patient Details");
    autoTable(doc, {
      startY: 28,
      head: [["Field", "Value"]],
      body: [
        ["Name", ctx.patient.name],
        ["Age", String(ctx.patient.age ?? "—")],
        ["Gender", ctx.patient.gender ?? "—"],
        ["Contact", ctx.patient.contact ?? "—"],
      ],
      headStyles: { fillColor: BRAND.color },
    });
  }

  // ====== Executive Summary ======
  if (ctx.sections.executive) {
    doc.addPage();
    header(doc, "Executive Summary");
    const s = ctx.sections.executive;
    autoTable(doc, {
      startY: 28,
      head: [["Metric", "Value"]],
      body: [
        ["Total Predictions", String(s.total)],
        ["Low Risk", String(s.low)],
        ["Medium Risk", String(s.medium)],
        ["High Risk", String(s.high)],
      ],
      headStyles: { fillColor: BRAND.color },
    });
  }

  // ====== Predictions ======
  if (ctx.sections.predictions && ctx.sections.predictions.length) {
    doc.addPage();
    header(doc, "Prediction History");
    autoTable(doc, {
      startY: 28,
      head: [["Date", "Disease", "Risk Level", "Score", "Confidence", "Model"]],
      body: ctx.sections.predictions.map((p) => [
        new Date(p.created_at).toLocaleDateString(),
        p.disease_type,
        (p.risk_level ?? "—").toUpperCase(),
        p.risk_score != null ? `${Math.round(p.risk_score * 100)}%` : "—",
        p.confidence != null ? `${Math.round(p.confidence * 100)}%` : "—",
        p.model_used ?? "—",
      ]),
      headStyles: { fillColor: BRAND.color },
      styles: { fontSize: 8 },
    });
  }

  // ====== Models ======
  if (ctx.sections.models && ctx.sections.models.length) {
    doc.addPage();
    header(doc, "Model Performance");
    autoTable(doc, {
      startY: 28,
      head: [["Model", "Disease", "Accuracy", "F1", "AUC-ROC"]],
      body: ctx.sections.models.map((m) => [
        m.model_name,
        m.disease_type ?? "—",
        m.accuracy != null ? m.accuracy.toFixed(3) : "—",
        m.f1_score != null ? m.f1_score.toFixed(3) : "—",
        m.auc_roc != null ? m.auc_roc.toFixed(3) : "—",
      ]),
      headStyles: { fillColor: BRAND.color },
    });
  }

  // ====== Feature Importance ======
  if (ctx.sections.featureImportance) {
    doc.addPage();
    header(doc, "Feature Importance");
    autoTable(doc, {
      startY: 28,
      head: [["Feature", "Impact"]],
      body: Object.entries(ctx.sections.featureImportance)
        .sort((a, b) => b[1] - a[1])
        .map(([k, v]) => [k, `${Math.round(v * 100)}%`]),
      headStyles: { fillColor: BRAND.color },
    });
  }

  // ====== Recommendations ======
  if (ctx.sections.recommendations && ctx.sections.recommendations.length) {
    doc.addPage();
    header(doc, "Recommendations");
    let yy = 32;
    doc.setFontSize(10);
    ctx.sections.recommendations.forEach((r, i) => {
      const split = doc.splitTextToSize(`${i + 1}. ${r}`, w - 28);
      doc.text(split, 14, yy);
      yy += split.length * 5 + 3;
    });
  }

  footer(doc);
  return doc;
}

export function downloadReport(ctx: ReportContext, filename?: string) {
  const doc = generateReportPdf(ctx);
  doc.save(filename ?? `${ctx.type}-report-${Date.now()}.pdf`);
}
