/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PredictFullRouteImport } from './routes/predict-full'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiMlIndexRouteImport } from './routes/api.ml.index'
import { Route as ApiMlRecommendationsRouteImport } from './routes/api.ml.recommendations'
import { Route as ApiMlModelsRouteImport } from './routes/api.ml.models'
import { Route as ApiMlMetricsRouteImport } from './routes/api.ml.metrics'
import { Route as ApiMlHealthScoreRouteImport } from './routes/api.ml.health-score'
import { Route as ApiMlHealthRouteImport } from './routes/api.ml.health'
import { Route as ApiMlAnalyticsRouteImport } from './routes/api.ml.analytics'
import { Route as ApiMlPredictFullAssessmentRouteImport } from './routes/api.ml.predict.full-assessment'
import { Route as ApiMlPredictDiseaseRouteImport } from './routes/api.ml.predict.$disease'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictFullRoute = PredictFullRouteImport.update({
  id: '/predict-full',
  path: '/predict-full',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlIndexRoute = ApiMlIndexRouteImport.update({
  id: '/api/ml/',
  path: '/api/ml/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlRecommendationsRoute = ApiMlRecommendationsRouteImport.update({
  id: '/api/ml/recommendations',
  path: '/api/ml/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlModelsRoute = ApiMlModelsRouteImport.update({
  id: '/api/ml/models',
  path: '/api/ml/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlMetricsRoute = ApiMlMetricsRouteImport.update({
  id: '/api/ml/metrics',
  path: '/api/ml/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlHealthScoreRoute = ApiMlHealthScoreRouteImport.update({
  id: '/api/ml/health-score',
  path: '/api/ml/health-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlHealthRoute = ApiMlHealthRouteImport.update({
  id: '/api/ml/health',
  path: '/api/ml/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlAnalyticsRoute = ApiMlAnalyticsRouteImport.update({
  id: '/api/ml/analytics',
  path: '/api/ml/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlPredictFullAssessmentRoute =
  ApiMlPredictFullAssessmentRouteImport.update({
    id: '/api/ml/predict/full-assessment',
    path: '/api/ml/predict/full-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMlPredictDiseaseRoute = ApiMlPredictDiseaseRouteImport.update({
  id: '/api/ml/predict/$disease',
  path: '/api/ml/predict/$disease',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/predict': typeof PredictRoute
  '/predict-full': typeof PredictFullRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$id': typeof PatientsIdRoute
  '/api/ml/analytics': typeof ApiMlAnalyticsRoute
  '/api/ml/health': typeof ApiMlHealthRoute
  '/api/ml/health-score': typeof ApiMlHealthScoreRoute
  '/api/ml/metrics': typeof ApiMlMetricsRoute
  '/api/ml/models': typeof ApiMlModelsRoute
  '/api/ml/recommendations': typeof ApiMlRecommendationsRoute
  '/api/ml/': typeof ApiMlIndexRoute
  '/api/ml/predict/$disease': typeof ApiMlPredictDiseaseRoute
  '/api/ml/predict/full-assessment': typeof ApiMlPredictFullAssessmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/predict': typeof PredictRoute
  '/predict-full': typeof PredictFullRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$id': typeof PatientsIdRoute
  '/api/ml/analytics': typeof ApiMlAnalyticsRoute
  '/api/ml/health': typeof ApiMlHealthRoute
  '/api/ml/health-score': typeof ApiMlHealthScoreRoute
  '/api/ml/metrics': typeof ApiMlMetricsRoute
  '/api/ml/models': typeof ApiMlModelsRoute
  '/api/ml/recommendations': typeof ApiMlRecommendationsRoute
  '/api/ml': typeof ApiMlIndexRoute
  '/api/ml/predict/$disease': typeof ApiMlPredictDiseaseRoute
  '/api/ml/predict/full-assessment': typeof ApiMlPredictFullAssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/predict': typeof PredictRoute
  '/predict-full': typeof PredictFullRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$id': typeof PatientsIdRoute
  '/api/ml/analytics': typeof ApiMlAnalyticsRoute
  '/api/ml/health': typeof ApiMlHealthRoute
  '/api/ml/health-score': typeof ApiMlHealthScoreRoute
  '/api/ml/metrics': typeof ApiMlMetricsRoute
  '/api/ml/models': typeof ApiMlModelsRoute
  '/api/ml/recommendations': typeof ApiMlRecommendationsRoute
  '/api/ml/': typeof ApiMlIndexRoute
  '/api/ml/predict/$disease': typeof ApiMlPredictDiseaseRoute
  '/api/ml/predict/full-assessment': typeof ApiMlPredictFullAssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/datasets'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/models'
    | '/patients'
    | '/predict'
    | '/predict-full'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/api/chat'
    | '/patients/$id'
    | '/api/ml/analytics'
    | '/api/ml/health'
    | '/api/ml/health-score'
    | '/api/ml/metrics'
    | '/api/ml/models'
    | '/api/ml/recommendations'
    | '/api/ml/'
    | '/api/ml/predict/$disease'
    | '/api/ml/predict/full-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/datasets'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/models'
    | '/patients'
    | '/predict'
    | '/predict-full'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/api/chat'
    | '/patients/$id'
    | '/api/ml/analytics'
    | '/api/ml/health'
    | '/api/ml/health-score'
    | '/api/ml/metrics'
    | '/api/ml/models'
    | '/api/ml/recommendations'
    | '/api/ml'
    | '/api/ml/predict/$disease'
    | '/api/ml/predict/full-assessment'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/datasets'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/models'
    | '/patients'
    | '/predict'
    | '/predict-full'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/api/chat'
    | '/patients/$id'
    | '/api/ml/analytics'
    | '/api/ml/health'
    | '/api/ml/health-score'
    | '/api/ml/metrics'
    | '/api/ml/models'
    | '/api/ml/recommendations'
    | '/api/ml/'
    | '/api/ml/predict/$disease'
    | '/api/ml/predict/full-assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DatasetsRoute: typeof DatasetsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PredictRoute: typeof PredictRoute
  PredictFullRoute: typeof PredictFullRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMlAnalyticsRoute: typeof ApiMlAnalyticsRoute
  ApiMlHealthRoute: typeof ApiMlHealthRoute
  ApiMlHealthScoreRoute: typeof ApiMlHealthScoreRoute
  ApiMlMetricsRoute: typeof ApiMlMetricsRoute
  ApiMlModelsRoute: typeof ApiMlModelsRoute
  ApiMlRecommendationsRoute: typeof ApiMlRecommendationsRoute
  ApiMlIndexRoute: typeof ApiMlIndexRoute
  ApiMlPredictDiseaseRoute: typeof ApiMlPredictDiseaseRoute
  ApiMlPredictFullAssessmentRoute: typeof ApiMlPredictFullAssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict-full': {
      id: '/predict-full'
      path: '/predict-full'
      fullPath: '/predict-full'
      preLoaderRoute: typeof PredictFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/': {
      id: '/api/ml/'
      path: '/api/ml'
      fullPath: '/api/ml/'
      preLoaderRoute: typeof ApiMlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/recommendations': {
      id: '/api/ml/recommendations'
      path: '/api/ml/recommendations'
      fullPath: '/api/ml/recommendations'
      preLoaderRoute: typeof ApiMlRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/models': {
      id: '/api/ml/models'
      path: '/api/ml/models'
      fullPath: '/api/ml/models'
      preLoaderRoute: typeof ApiMlModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/metrics': {
      id: '/api/ml/metrics'
      path: '/api/ml/metrics'
      fullPath: '/api/ml/metrics'
      preLoaderRoute: typeof ApiMlMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/health-score': {
      id: '/api/ml/health-score'
      path: '/api/ml/health-score'
      fullPath: '/api/ml/health-score'
      preLoaderRoute: typeof ApiMlHealthScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/health': {
      id: '/api/ml/health'
      path: '/api/ml/health'
      fullPath: '/api/ml/health'
      preLoaderRoute: typeof ApiMlHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/analytics': {
      id: '/api/ml/analytics'
      path: '/api/ml/analytics'
      fullPath: '/api/ml/analytics'
      preLoaderRoute: typeof ApiMlAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/predict/full-assessment': {
      id: '/api/ml/predict/full-assessment'
      path: '/api/ml/predict/full-assessment'
      fullPath: '/api/ml/predict/full-assessment'
      preLoaderRoute: typeof ApiMlPredictFullAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/predict/$disease': {
      id: '/api/ml/predict/$disease'
      path: '/api/ml/predict/$disease'
      fullPath: '/api/ml/predict/$disease'
      preLoaderRoute: typeof ApiMlPredictDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DatasetsRoute: DatasetsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PredictRoute: PredictRoute,
  PredictFullRoute: PredictFullRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMlAnalyticsRoute: ApiMlAnalyticsRoute,
  ApiMlHealthRoute: ApiMlHealthRoute,
  ApiMlHealthScoreRoute: ApiMlHealthScoreRoute,
  ApiMlMetricsRoute: ApiMlMetricsRoute,
  ApiMlModelsRoute: ApiMlModelsRoute,
  ApiMlRecommendationsRoute: ApiMlRecommendationsRoute,
  ApiMlIndexRoute: ApiMlIndexRoute,
  ApiMlPredictDiseaseRoute: ApiMlPredictDiseaseRoute,
  ApiMlPredictFullAssessmentRoute: ApiMlPredictFullAssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
